import React from "react";

const features = [
  {
    title: "AI-Powered Learning",
    description:
      "Personalized recommendations, flashcards, and quizzes generated by AI.",
  },
  {
    title: "Live Classes & Chat",
    description:
      "Real-time interaction with teachers and peers via live video and chat.",
  },
  {
    title: "Progress Tracking",
    description:
      "Track your learning journey and achievements across all courses.",
  },
  {
    title: "Secure Payments",
    description:
      "Purchase courses and subscriptions securely with Stripe or Razorpay.",
  },
];

const testimonials = [
  {
    name: "Jane Doe",
    role: "Student",
    quote:
      "Tutorly helped me ace my exams with its smart quizzes and easy-to-follow lessons!",
  },
  {
    name: "John Smith",
    role: "Teacher",
    quote:
      "The live class and progress tracking features make teaching online a breeze.",
  },
];

export default function Landing() {
  return (
    <div className="bg-white min-h-screen font-sans">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-600 to-indigo-700 text-white py-20 px-4 text-center">
        <h1 className="text-4xl md:text-6xl font-bold mb-4">Tutorly</h1>
        <p className="text-xl md:text-2xl mb-8 max-w-2xl mx-auto">
          The AI-powered learning platform for students and teachers. Learn,
          teach, and grow with personalized courses, quizzes, and live classes.
        </p>
        <a
          href="#get-started"
          className="inline-block bg-white text-blue-700 font-semibold px-8 py-3 rounded-full shadow-lg hover:bg-blue-100 transition"
        >
          Get Started
        </a>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-10 text-gray-800">
          Features
        </h2>
        <div className="grid md:grid-cols-2 gap-8">
          {features.map((feature, idx) => (
            <div
              key={idx}
              className="bg-gray-50 p-6 rounded-xl shadow hover:shadow-lg transition"
            >
              <h3 className="text-xl font-semibold mb-2 text-blue-700">
                {feature.title}
              </h3>
              <p className="text-gray-700">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="bg-gray-100 py-16 px-4">
        <h2 className="text-3xl font-bold text-center mb-10 text-gray-800">
          What Our Users Say
        </h2>
        <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-8">
          {testimonials.map((t, idx) => (
            <div
              key={idx}
              className="bg-white p-6 rounded-xl shadow text-center"
            >
              <p className="text-lg italic mb-4">“{t.quote}”</p>
              <div className="font-semibold text-blue-700">{t.name}</div>
              <div className="text-gray-500 text-sm">{t.role}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Call to Action */}
      <section
        id="get-started"
        className="py-16 px-4 text-center bg-gradient-to-br from-indigo-700 to-blue-600 text-white"
      >
        <h2 className="text-3xl font-bold mb-4">
          Ready to start learning or teaching?
        </h2>
        <p className="mb-8 text-lg max-w-xl mx-auto">
          Join Tutorly today and unlock the power of AI-driven education.
        </p>
        <a
          href="#"
          className="inline-block bg-white text-blue-700 font-semibold px-8 py-3 rounded-full shadow-lg hover:bg-blue-100 transition"
        >
          Sign Up Now
        </a>
      </section>
    </div>
  );
}
